services:
  postgres:
    container_name: postgres-gs-app
    image: postgres
    environment:
      POSTGRES_USER: cidi
      POSTGRES_PASSWORD: passer
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: game_store_app_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres:
    driver: local